# Copyright 2005 - 2026 Advantage Solutions, s. r. o.
#
# This file is part of ORIGAM (http://www.origam.org).
#
# ORIGAM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ORIGAM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ORIGAM. If not, see <http://www.gnu.org/licenses/>.

name: Docker Build

on:
  pull_request:
    branches:
      - master

concurrency:
  group: docker-build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  build:
    name: Build image

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: origam/xsl-fo-server:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max
